services:
  ct-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: crafting
      POSTGRES_PASSWORD: crafting
      POSTGRES_ROOT_PASSWORD: crafting
      POSTGRES_USER: crafting
    ports:
      - "5440:5432"